# Constants
NUM_CYCLES = 73 * 52  # 73 years in weeks
RIAL_USD_PRICE = 853_661  # TGJU IRR/USD
PRICE_PER_UI_FACTOR_VIII = 58_000  # IRR, FDA
STANDARD_PROPHYLAXIS_WEEKLY_DOSE = 25 * 2  # IR Protocol
HIGH_DOSE_PROPHYLAXIS_WEEKLY_DOSE = 30 * 3  # IR Protocol
BLEEDING_DOSE = 30 * 4  #  Guideline average
JOINT_BLEEDING_DOSE = 30 * 2  #  Guideline average
LT_BLEEDING_DOSE = 550  #  Guideline average
WILLINGNESS_TO_PAY_THRESHOLD = 4_500  # USD

# Will be ignored if None value passthrough
DISCOUNT_RATE_WEEKLY = None
# DISCOUNT_RATE_WEEKLY = ((1 + 0.035) ** (1 / 52)) - 1

PPP_CONVERSION_FACTOR = 117_170  # World Bank 2024 IRR/USD, PPP
# PPP_CONVERSION_FACTOR = 165_354  # Y_CHART | IMF 2025 IRR/USD, PPP
