from app.notebook.calibration import build_calibration_report, classify_calibration
from app.notebook.dataframe_builders import build_df, calculate_state_occupation
from app.notebook.display import show
from app.notebook.iran_mortality import (
    POLAND_AGE_BUCKETS,
    WPP_AGE_START_TO_POLAND,
    WPP_OPEN_AGE_STARTS,
    WPP_VALUE_COL,
    aggregate_to_poland_buckets,
    build_mortality_from_wpp,
    build_mortality_table,
    compare_to_reference,
    compute_cohort_mortality,
    compute_crude_annual_rate,
    load_iran_population,
    load_wpp_mortality,
    merge_cohort_with_wpp,
    validate_mortality_table,
    write_mortality_json,
)
from app.notebook.parameter_sets import HemophiliaParamRepo
from app.notebook.scenario_helpers import (
    define_scenario_extension,
    extend_scenario,
    get_base_pair_key,
    get_parameter_label,
    get_tornado_ranges,
    insert_scenario,
    pair_scenarios,
    parse_scenario,
    split_tornado_extensions,
)
from app.notebook.scenario_runner import batch_generator, run_scenarios_in_batches
from app.notebook.storage import store

__all__ = [
    "classify_calibration",
    "build_calibration_report",
    "calculate_state_occupation",
    "build_df",
    "show",
    "POLAND_AGE_BUCKETS",
    "WPP_AGE_START_TO_POLAND",
    "WPP_OPEN_AGE_STARTS",
    "WPP_VALUE_COL",
    "aggregate_to_poland_buckets",
    "build_mortality_from_wpp",
    "build_mortality_table",
    "compare_to_reference",
    "compute_cohort_mortality",
    "compute_crude_annual_rate",
    "load_iran_population",
    "load_wpp_mortality",
    "merge_cohort_with_wpp",
    "validate_mortality_table",
    "write_mortality_json",
    "HemophiliaParamRepo",
    "insert_scenario",
    "parse_scenario",
    "pair_scenarios",
    "extend_scenario",
    "define_scenario_extension",
    "split_tornado_extensions",
    "get_tornado_ranges",
    "get_parameter_label",
    "get_base_pair_key",
    "batch_generator",
    "run_scenarios_in_batches",
    "store",
]
